# 1. Import Package

In [1]:
import numpy as np

# 2. Read Dataset

In [2]:
dataset = np.loadtxt('../dataset/watermelon_data_set_3_alpha.csv', delimiter='|')

dataset

array([[ 0.   ,  0.697,  0.46 ,  1.   ],
       [ 1.   ,  0.774,  0.376,  1.   ],
       [ 2.   ,  0.634,  0.264,  1.   ],
       [ 3.   ,  0.608,  0.318,  1.   ],
       [ 4.   ,  0.556,  0.215,  1.   ],
       [ 5.   ,  0.403,  0.237,  1.   ],
       [ 6.   ,  0.481,  0.149,  1.   ],
       [ 7.   ,  0.437,  0.221,  1.   ],
       [ 8.   ,  0.666,  0.091,  0.   ],
       [ 9.   ,  0.243,  0.267,  0.   ],
       [10.   ,  0.245,  0.057,  0.   ],
       [11.   ,  0.343,  0.099,  0.   ],
       [12.   ,  0.639,  0.161,  0.   ],
       [13.   ,  0.657,  0.198,  0.   ],
       [14.   ,  0.36 ,  0.37 ,  0.   ],
       [15.   ,  0.593,  0.042,  0.   ],
       [16.   ,  0.719,  0.103,  0.   ]])

# 3. LDA

In [64]:
def LDA(inputs):
    """
    Params:
        inputs : array - [values of x, y]
    """
    m = inputs.shape[0]
    input_x = inputs[:, 0:-1].T
    y_col = inputs.shape[1] - 1
    
    u0 = inputs[inputs[:, y_col] == 0].mean(axis=0)[:y_col]
    u1 = inputs[inputs[:, y_col] == 1].mean(axis=0)[:y_col]
    
    u0 = u0.reshape(u0.shape[0], 1)
    u1 = u1.reshape(u1.shape[0], 1)
    
    # Scatter matrix
    s_w = np.zeros((u0.shape[0], u0.shape[0]))
    s_b = np.dot((u0 - u1), (u0 - u1).T)
    
    for i in range(m):
        if inputs[i][-1] == 0:
            ut = u0
        else:
            ut = u1
        
        xt = inputs[i,:-1]
        xt = xt.reshape(xt.shape[0], 1)
        s_w += np.dot((xt - ut), (xt - ut).T)
#         print(xt)
    
    w = np.dot(np.linalg.inv(s_w), (u0 - u1))
    Z = np.dot(w.T, input_x)
#     print((u0 - u1).shape)
    
    return Z, w

# 4. Predict

In [65]:
predict, w = LDA(dataset[:, 1:])

In [66]:
predict, w

(array([[-0.44975175, -0.39789997, -0.29279779, -0.32961409, -0.244333  ,
         -0.23822553, -0.18350939, -0.23121446, -0.16724645, -0.23710573,
         -0.07924161, -0.12539864, -0.21596487, -0.2464991 , -0.3320207 ,
         -0.11952273, -0.18413951]]),
 array([[-0.14821353],
        [-0.75314548]]))